version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/ner/stanford-ner-service

permissions:
  - object: /home/ec2-user/ner/
    pattern: "stanford-ner-service"
    owner: ec2-user
    group: ec2-user
    mode: 775

  - object: /home/ec2-user/ner/stanford-ner-service/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 775

hooks:
#  ApplicationStop:
#    - location: /etc/init.d/stanford-nerd stop
#      timeout: 20
#

  BeforeInstall:
    - location: /etc/profile.d/env.sh
      timeout: 10

  AfterInstall:
    - location: /ner-install.sh /home/ec2-user/ner/stanford-ner-service/
      timeout: 900

  ApplicationStart:
    - location: /etc/init.d/stanford-nerd start
      timeout: 20
